######################################################################
# Automatically generated by qmake (2.01a) ?? 6? 27 18:12:09 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.c
QT += widgets gui
